got logout button to work
VictoriaSweet/scary-potato pull request #39
Opened 2023-11-20 22:13 UTC by derekm129

2023-11-20 23:25 UTC, VictoriaSweet requested changes
can you please review and pull my latest pull request regarding homeroutes, it will show on the local server, currently with the way the files were set on the previous commit, it will not display on live host, then we can test it and repush it

2023-11-21 00:40 UTC, Deazymat approved these changes

2023-11-21 00:41 UTC, Deazymat commented
LG

2023-11-21 00:48 UTC, VictoriaSweet approved these changes

2023-11-21 01:50 UTC, Deazymat approved these changes
Good

2023-11-21 01:50 UTC, merged